import { Product } from "../lib/types";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Test Brewery",
    brewery_type: "Micro",
    address_1: "123 Main St",
    address_2: null,
    address_3: null,
    city: "Test City",
    state_province: "Test State",
    postal_code: "12345",
    country: "Test Country",
    longitude: null,
    latitude: null,
    phone: "123-456-7890",
    website_url: "http://testbrewery.com",
    state: null,
    street: null,
  },
  {
    id: "2",
    name: "Test Brewery2",
    brewery_type: "Brewpub",
    address_1: "456 Elm St",
    address_2: null,
    address_3: null,
    city: "Another City",
    state_province: "Another State",
    postal_code: "67890",
    country: "Another Country",
    longitude: null,
    latitude: null,
    phone: "987-654-3210",
    website_url: "http://testbrewery2.com",
    state: null,
    street: null,
  },
];
